[project]
name = "coral-completion-seg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate",
    "coral-schemas",
    "fastapi[standard]",
    "geco",
    "huggingface-hub>=1.3.0",
    "opencv-python",
    "plotly",
    "pycocotools",
    "pydantic",
    "scikit-learn",
    "scipy-stubs",
    "tqdm",
    "transformers",
]

[tool.uv.sources]
transformers = { git = "https://github.com/huggingface/transformers.git" }
geco = { git = "https://github.com/robertleist/GeCo.git" }
coral-schemas = { git = "ssh://git@github.com/yapat-app/coral-schemas.git" }
